version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:eoan"
    steps:
      - checkout
      - run:
          name: System setup
          command: |
            apt update && apt install -y python3-pip cmake gcc-9 git curl tar
            curl -sSL https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.tar.gz -o cmake.tar.gz
            tar xf cmake.tar.gz --strip 1 -C /usr/local
            pip3 install --upgrade pip
            pip3 install conan
      - run:
          name: Configure
          command: |
            ls -al
            git status
            conan install . -pr .conan/profiles/gcc-9 -if build --build missing \
                -s build_type=Debug
            cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Debug
            cmake --build build
            ctest
