name: Build linux

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - master
      - devel

jobs:
  linux:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-20.04-gcc-10]

        include:
          - name: ubuntu-20.04-gcc-10
            os: ubuntu-20.04
            compiler: gcc
            version: 10

    steps:
      - uses: actions/checkout@v1
      - name: System setup
        run: |
          set -xe

          sudo apt-get update
          sudo apt-get install cmake

          # install required gcc version
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo -- Installing gcc-${{ matrix.version }}...
            sudo apt-get install -y g++-${{ matrix.version }}
            sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-${{ matrix.version }} 100
            sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-${{ matrix.version }} 100
          fi

          echo -- Installing setuptools, pip, wheel and conan
          sudo apt install -y python3-setuptools python3-pip
          sudo -H pip3 install wheel
          sudo -H pip3 install conan

          conan remote add xdev https://api.bintray.com/conan/6l20garcia/xdev

      - name: Run test build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DXDEV_UNIT_TESTING=ON ..
          make -j
          ctest
