name: Build windows

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - master
      - devel
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - master
      - devel

jobs:
  windows:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [windows-2019]

        include:
          - name: windows-2019
            os: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install conan
    - name: Run test build
      run: |
        mkdir build
        cd build
        conan install .. -s build_type=Debug --build missing
        cmake -DCMAKE_BUILD_TYPE=Debug -DXDEV_UNIT_TESTING=ON -DXDEV_CORE_NO_TEST_VARIANT=ON ..
        cmake --build . --config Debug
        cmake --build . --config Debug --target RUN_TESTS
    - name: Build conan package
      run: |
        conan create . -s build_type=Debug --build missing
