name: Conan packages

on:
  push:
    tags:
       - v*

jobs:
  linux:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CONAN_XDEV_TOKEN: ${{ secrets.CONAN_XDEV_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        name:
          - ubuntu-20.04-gcc-10-debug
          - ubuntu-20.04-gcc-10-release

        include:

          - name: ubuntu-20.04-gcc-10-debug
            os: ubuntu-20.04
            compiler: gcc
            version: 10
            build_type: Debug

          - name: ubuntu-20.04-gcc-10-release
            os: ubuntu-20.04
            compiler: gcc
            version: 10
            build_type: Release

    steps:
      - uses: actions/checkout@v1
      - name: System setup
        run: |
          set -xe

          sudo apt-get update
          sudo apt-get install cmake

          # install required gcc version
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo -- Installing gcc-${{ matrix.version }}...
            sudo apt-get install -y g++-${{ matrix.version }}
            sudo update-alternative --install /usr/bin/c++ c++ /usr/bin/g++-${{ matrix.version }} 100
            sudo update-alternative --install /usr/bin/cc cc /usr/bin/gcc-${{ matrix.version }} 100
          fi

          echo -- Installing setuptools, pip, wheel and conan
          sudo apt install -y python3-setuptools python3-pip
          sudo -H pip3 install wheel
          sudo -H pip3 install conan

          conan remote add xdev https://api.bintray.com/conan/6l20garcia/xdev

      - name: Build conan package
        run: |
          set -xe
          git clean -fd
          conan create . -s build_type=${{ matrix.build_type }} --profile=./.conan/profiles/${{ matrix.compiler }}-${{ matrix.version }} --build missing
          conan user -p ${CONAN_XDEV_TOKEN} -r xdev 6l20garcia
          conan upload --all --confirm -r xdev xdev-core

  # # Maybe one day xdev will support msvc... nobody knows
  # windows:
  #   name: ${{ matrix.name }}
  #   runs-on: ${{ matrix.os }}
  #
  #   env:
  #     CONAN_XDEV_TOKEN: ${{ secrets.CONAN_XDEV_TOKEN }}
  #
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       name:
  #         - windows-2019-debug
  #         - windows-2019-release
  #
  #       include:
  #
  #         - name: windows-2019-debug
  #           os: windows-2019
  #           build_type: Debug
  #
  #         - name: windows-2019-release
  #           os: windows-2019
  #           build_type: Release
  #
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Set up Python 3
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3
  #   - name: System setup
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install conan
  #       conan remote add xdev https://api.bintray.com/conan/6l20garcia/xdev
  #   - name: Build conan package
  #     run: |
  #       git clean -fd
  #       conan create . -s build_type=${{ matrix.build_type }} --build missing
  #       conan user -p ${CONAN_XDEV_TOKEN} -r xdev 6l20garcia
  #       conan upload --all --confirm -r xdev xdev-core
